name: Transcribe and save

on:
  schedule:
    - cron: '0 7 * * 1-5' # This will run the action every weekday at 7 AM
  workflow_dispatch:
    

jobs:
  run-python-script:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install ffmpeg

    - name: Run Python script
      run: python Code/script.py
      
    - name: Commit changes
      run: |
        git config --global user.email "github-action-bot@users.noreply.github.com"
        git config --global user.name "GitHub Action Bot"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Automatically add more transcripts"
        git push
