name: Transcribe and save

on:
  schedule:
    - cron: '0 7 * * 1-5' # This will run the action every weekday at 7 AM
  workflow_dispatch:
    

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: python Code/script.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions@example.com"
        git add Data/.
        git diff --quiet && git diff --staged --quiet || git commit -m "Transcribe Data"
        git push
